# -*- coding: utf-8 -*-
"""Final_Project_Phishing_Email_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ngwDW3UN2KK75vjz_0lVESkU6XNH_ppu

Fine-tuning:
https://huggingface.co/docs/transformers/tasks/sequence_classification
https://huggingface.co/docs/transformers/en/training
https://huggingface.co/docs/transformers/en/models
"""

from huggingface_hub import login

login()

import pandas as pd

df = pd.read_csv("phishing_dataset.csv")

from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_name = "distilbert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name)

from datasets import load_dataset
from transformers import AutoTokenizer


dataset = load_dataset("csv", data_files="phishing_dataset.csv")["train"]

dataset = dataset.train_test_split(test_size=0.1)

def tokenize(batch):
    return tokenizer(
        batch["email"],
        truncation=True,
        padding="max_length",
        max_length=512
    )

tokenized_dataset = dataset.map(tokenize, batched=True)

def preprocess_function(examples):
    return tokenizer(examples["text"], truncation=True)

from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

import numpy as np


def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return accuracy.compute(predictions=predictions, references=labels)

"""Training

"""

id2label = {0: "SAFE", 1: "PHISHING"}
label2id = {"SAFE": 0, "PHISHING": 1}

from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2,
    id2label=id2label,
    label2id=label2id
)

!pip install evaluate

import evaluate

accuracy = evaluate.load("accuracy")

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="phishing_model",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=2,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True
)
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    data_collator=data_collator,
    compute_metrics=compute_metrics
)
trainer.train()

trainer.save_model("phishing_model")
tokenizer.save_pretrained("phishing_model")

"""Walk through:

"""

from transformers import AutoModelForSequenceClassification
import torch

text = "Hey, just confirming our meeting is still scheduled for 3pm tomorrow. Let me know if anything changes."

tokenizer = AutoTokenizer.from_pretrained("phishing_model")
model = AutoModelForSequenceClassification.from_pretrained("phishing_model")
inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=512)

with torch.no_grad():
    logits = model(**inputs).logits

pred = torch.argmax(logits).item()

print("Final prediction: ", pred)